[package]
name = "kostka"
version = "0.1.0"
authors = ["Sekky61 <misa@majer.cz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
itertools = "0.10.1"
